
local globals = require "main.globals"

function init(self)
	-- Add initialization code here
	-- Remove this function if not needed
	self.lifeTime = 0
	--pprint(go.get_rotation())
end

function final(self)
	-- Add finalization code here
	-- Remove this function if not needed
end

function update(self, dt)

	if globals.getPause() then
		return
	end
	
	self.lifeTime= self.lifeTime + dt
	if self.lifeTime > 0.1 then
		go.delete()
	end
	-- Add update code here
	-- Remove this function if not needed

	-- DRAW ORDER
	g_applyDrawOrder(go.get_id(), 3)
end

function on_message(self, message_id, message, sender)
	
end

function on_input(self, action_id, action)
	-- Add input-handling code here
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Remove this function if not needed
end
