--Temporary script to test if enemies are spawned properly

local enemyManager = require "arena.enemyManager"
function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	if action_id == hash("temp") then
		--How much enemies are to spawn
		enemyManager.initializeEnemies(10)
	elseif action_id == hash("wave") then
		enemyManager.initializeWave(1, 10, 1)
	end
end
