--KNIGHT
go.property("shootingDelay", 0.35) 

function init(self)
	self.shootingTimer = 0
	self.isShooting = false
	self.shootingDir = vmath.vector3(0, 0, 0)
end

function update(self, dt)
	--Shooting
	if self.isShooting and self.shootingTimer <= 0 then
		self.shootingDir = vmath.normalize(self.shootingDir)
		local l_angle = math.atan2(self.shootingDir.y, self.shootingDir.x)
		factory.create("#attackFactory", nil, vmath.quat_rotation_z(l_angle), { projectileDir = self.shootingDir, makerID = msg.url() })
		self.shootingTimer = self.shootingDelay
	else
		self.shootingTimer = self.shootingTimer - dt
	end

	--Reset flags
	self.isShooting = false
end

function on_message(self, message_id, message, sender)
	if message_id == hash("shoot") then
		self.isShooting = true
		self.shootingDir = vmath.vector3(message.x, message.y, 0)
	end
end