go.property("dir", vmath.vector3())

local function explode(self)
	self.life = 1000
	go.set_rotation(vmath.quat())
	self.speed = 0
end

function init(self)
	self.speed = 300
	self.life = 1
end

function update(self, dt)
	local pos = go.get_position()
	pos = pos + self.dir * self.speed * dt
	go.set_position(pos)

	self.life = self.life - dt

	if(self.life <= 0) then
		msg.post("#rangeAttack", "kill_particle")
	end 
end

function on_message(self, message_id, message, sender)
	if message_id == hash("kill_particle") then
		go.delete()
	elseif message_id == hash("collision_response") then
		--COLLISION WITH ENEMY OR ARENA OBJECT
		--CHECK rangeAttack.go
		go.delete()
	end
end

