local globals = require "main.globals"
local playersManager = require "player.playersManager"

go.property("damage", 15)

function init(self)
	self.projectileSpeed = 50
	self.projectileSpeedByDistanceMultiplier = 0.2
	self.projectileLife = 10
end

function update(self, dt)
	if playersManager.getActivePlayersIDs() ~= 0 then
		local enemyPos = go.get_position()
		local closestPlayerID = playersManager.getClosestPlayerID(enemyPos)
		local closestPlayerPos = playersManager.getPlayerPos(closestPlayerID)
		local distanceToClosestPlayer = vmath.length(closestPlayerPos - enemyPos)

		local positionDiffrenceAbs = (closestPlayerPos - enemyPos)
		positionDiffrenceAbs.x = math.abs(positionDiffrenceAbs.x)
		positionDiffrenceAbs.y = math.abs(positionDiffrenceAbs.y)

		local positionDiffrence = (closestPlayerPos - enemyPos)

		local movingDir = vmath.vector3(positionDiffrence.x,positionDiffrence.y, 0)
		movingDir = vmath.normalize(movingDir)

		enemyPos = enemyPos + movingDir * (self.projectileSpeed + distanceToClosestPlayer * self.projectileSpeedByDistanceMultiplier) * dt
		go.set_position(enemyPos)
	end	

	self.projectileLife = self.projectileLife - dt

	if(self.projectileLife <= 0) then
		go.delete()
	end 
end

function on_message(self, message_id, message, sender)
	if message_id == hash("collision_response") then
		if message.group == hash("players") then
			local enemyPos = go.get_position()
			local closestPlayerID = playersManager.getClosestPlayerID(enemyPos)
			--local playerUrl = closestPlayerID.."#player"
			local scriptUrl = msg.url(nil, closestPlayerID, "player")
			local playerHealth = go.get(scriptUrl, "health")
			--Send message about dealt damage
			msg.post(scriptUrl,"hit", {dmg = self.damage})
		end
		go.delete()
	end
	if message_id == hash("contact_point_response") then
		go.delete()
	end
end
