local shaderManager = require "managers/shaderManager"

function init(self)
	self.doOnce = false
	self.playerUrl = msg.url(nil,go.get_id(),"player")
	self.dashDir = vmath.vector3()
	self.isDashing = false
	self.dashRange = 200
	self.dashSpeed = 700
	self.dashTimer = self.dashRange / self.dashSpeed
	-- Remove this function if not needed
end

function update(self, dt)
	if self.dashTimer > 0 and self.isDashing then
		if not self.doOnce then
			self.doOnce = true
			--shaderManager.invisibilityEffect("#sprite", self.dashTimer)
		end

		go.set(self.playerUrl, "nonVulnerableTimer", 2*self.dashRange/self.dashSpeed)

		go.set(self.playerUrl, "isVulnerable", false)
		print( go.get(self.playerUrl, "position"))
		go.set(self.playerUrl,"position", go.get(self.playerUrl, "position") + self.dashSpeed * self.dashDir * dt)
		print( go.get(self.playerUrl, "position"))
		go.set_position(go.get(self.playerUrl, "position"))
		self.dashTimer = self.dashTimer - dt
	else
		self.doOnce = false
		self.isDashing = false
		self.dashTimer = self.dashRange / self.dashSpeed
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("dash") then
		self.isDashing = true
		self.dashDir = message.dir
	end
end