--Temporary script to test if enemies are spawned properly

local enemyManager = require "managers.enemyManager"

function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	if action_id == hash("temp") then
		--How much enemies are to spawn
		enemyManager.initializeEnemies(10)
	elseif action_id == hash("wave") then
		--Initialize wave (teleport precised amount of enemies to gates outside arena)
		enemyManager.initializeWave(10, 1)
	end
end
