--ARCHER
go.property("basicCD", 0.6)
go.property("basicCDmashing", 0.3)
--Skills CoolDowns
go.property("yellowCD", 0)
go.property("redCD", 0)
go.property("greenCD", 0)
go.property("blueCD", 0)

go.property("shootingDir", vmath.vector3(0,0,0))

--Flags
go.property("isShooting", false)
go.property("isYellowHit", false)
go.property("isRedHit", false)
go.property("isGreenHit", false)
go.property("isBlueHit", false)

go.property("isQuickHands", false)
go.property("quickHandsDuration", 7)

--Timers
go.property("quickHands_Timer", 0)
go.property("basicCD_Timer", 0)

--Button Timers
go.property("yellowCD_Timer", 0)
go.property("redCD_Timer", 0)
go.property("greenCD_Timer", 0)
go.property("blueCD_Timer", 0)

go.property("isMovementBase", true)

local attack = require "player/playerClasses/archer/attack.skillsModule"
local playerModule = require "player.playerModule"
local globals = require "main.globals"

function init(self)
	local CD = globals.getCD("archer")
	local url = msg.url(nil,go.get_id(),"player")
	self.baseMovingSpeed = go.get(url, "movingSpeed")
	self.yellowCD = CD.yellow
	self.redCD = CD.red
	self.greenCD = CD.green
	self.blueCD = CD.blue
	
	self.basicCD_Timer = 0
	self.isShooting = false
	self.shootingDir = vmath.vector3(0, 0, 0)
end

function update(self, dt)
	if globals.getPause() then
		return
	end

	attack.basic(self, dt)
	attack.arrowsCone(self, dt)
	attack.sniperShots(self, dt)
	attack.quickHands(self, dt)
	attack.powerArrow(self, dt)
end

function on_message(self, message_id, message, sender)
	if globals.getPause() then
		return
	end
	if message_id == hash("shoot") then
		self.isShooting = true
		self.shootingDir = vmath.vector3(message.x, message.y, 0)
	end
	if message_id == hash("stoppedShooting") then
		self.isShooting = false
	end

	if message_id == hash("btnYellow") then
		go.set("#player", "isBackTimer", 0)
		self.isYellowHit = true
	elseif message_id == hash("btnRed") then
		go.set("#player", "isBackTimer", 0)
		self.isRedHit = true
	elseif message_id == hash("btnGreen") then
		go.set("#player", "isBackTimer", 0)
		self.isGreenHit = true
	elseif message_id == hash("btnBlue") then
		go.set("#player", "isBackTimer", 0)
		self.isBlueHit = true
	end
end