--FireBreath
go.property("projectileDir", vmath.vector3())
go.property("range", 150)
go.property("speed", 200)
go.property("damage", 1)
go.property("life", 0)
go.property("lifeMult", 1)
go.property("alpha", 0)
local globals = require "main.globals"

function init(self)
	self.enemiesHit = {}
	self.life =  self.lifeMult * self.range/self.speed
end

function update(self, dt)
	go.set_position(go.get_position() + self.projectileDir * self.speed * dt)
	if self.life <= 0 then
		go.delete()
	else
		self.life = self.life - dt
	end 

	-- DRAW ORDER
	g_applyDrawOrder(go.get_id(), 2)
end

function on_message(self, message_id, message, sender)
	if globals.getPause() then
		return
	end
	--Destroy on hit
	if message_id == hash("collision_response") then
		if message.group == hash("enemy") then
			local url = msg.url(nil, message.other_id, "enemy")
			--msg.post(url, "knockback", {pos = go.get_position()})
			for i, enemy in pairs(self.enemiesHit) do
				if enemy == message.other_id then
					return
				end
			end	
			msg.post(url, "hit",{type = hash("plain"), damage = self.damage})

			table.insert(self.enemiesHit, message.other_id)
		else
			go.delete()
		end
	end
end