-- ENEMY MAGE ATTACKS CREATOR
local playersManager = require "managers.playersManager"
local globals = require "main.globals"

-- Global properties
go.property("shootingDelay", 5)

function init(self)
	-- Local settings
	self.isEnemyMageKilled = false
	self.shootingTimer = math.random(-5,0)
end

function update(self, dt)
	if globals.getPause() == false then
		if self.shootingTimer >= self.shootingDelay then
			if #playersManager.getActivePlayersIDs() > 0 then
				factory.create("#enemyMageHomingAttackFactory", nil)
			end
			self.shootingTimer = math.random(-1,1)
		else
			self.shootingTimer = self.shootingTimer + dt
		end
	end	
end